module.exports = {
  'likes': '{likes, number} me gusta',
  'logout': 'Salir',
  'english': 'Inglés',
  'spanish': 'Español',
  'french': 'Francés',
  'signup.subheading': 'Regístrate para ver el feed de otros usuarios',
  'signup.facebook': 'Iniciar sesión con Facebook',
  'signup.text': 'Iniciar sesión',
  'email': 'Correo eléctronico',
  'username': 'Nombra de usuario',
  'fullname': 'Nombre completo',
  'password': 'Contraseña',
  'signup.call-to-action': 'Regístrate',
  'signup.have-account': '¿Tienes una cuenta?',
  'signin': 'Entrar',
  'signin.not-have-account': '¿No tienes una cuenta?',
  'language': 'Idioma',
}
